CREATE TABLE `gangSheetArtwork` (
	`id` int AUTO_INCREMENT NOT NULL,
	`gangSheetId` int NOT NULL,
	`fileUrl` varchar(500) NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileSize` int,
	`mimeType` varchar(100),
	`originalWidth` int,
	`originalHeight` int,
	`dpi` int DEFAULT 300,
	`hasTransparency` int DEFAULT 0,
	`backgroundRemoved` int DEFAULT 0,
	`positionX` decimal(10,2) NOT NULL,
	`positionY` decimal(10,2) NOT NULL,
	`width` decimal(10,2) NOT NULL,
	`height` decimal(10,2) NOT NULL,
	`rotation` decimal(5,2) DEFAULT '0',
	`zIndex` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gangSheetArtwork_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gangSheets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`quantity` int NOT NULL DEFAULT 1,
	`status` enum('draft','submitted','approved','printing','completed','cancelled') NOT NULL DEFAULT 'draft',
	`exportFileUrl` varchar(500),
	`exportFileName` varchar(255),
	`exportFormat` enum('png','pdf') DEFAULT 'png',
	`previewImageUrl` varchar(500),
	`canvasWidth` int NOT NULL DEFAULT 900,
	`canvasHeight` int NOT NULL DEFAULT 3000,
	`totalPrice` decimal(10,2),
	`customerName` varchar(255),
	`customerEmail` varchar(320),
	`customerPhone` varchar(20),
	`customerCompany` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gangSheets_id` PRIMARY KEY(`id`)
);
