import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { getDb } from "./db";
import { orders } from "../drizzle/schema";
import { eq } from "drizzle-orm";
import { PayFastIntegration } from "./payfast-integration";

describe("Payment Processing", () => {
  let db: any;
  let testOrderId: number;
  let payfast: PayFastIntegration;

  beforeAll(async () => {
    db = await getDb();
    if (!db) throw new Error("Database not available");

    // Initialize PayFast
    payfast = new PayFastIntegration({
      merchantId: "test-merchant",
      merchantKey: "test-key",
      passphrase: "test-passphrase",
      isSandbox: true,
    });

    // Create a test order
    const result = await db.insert(orders).values({
      productId: 1,
      colorId: 1,
      sizeId: 1,
      quantity: 10,
      customerFirstName: "Payment",
      customerLastName: "Tester",
      customerEmail: "payment@test.com",
      customerPhone: "5555555555",
      totalPriceEstimate: "1000.00",
      depositAmount: "500.00",
      paymentMethod: "deposit",
      paymentStatus: "unpaid",
      status: "approved",
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    testOrderId = result[0].insertId;
  });

  afterAll(async () => {
    if (db && testOrderId) {
      await db.delete(orders).where(eq(orders.id, testOrderId));
    }
  });

  describe("PayFast Integration", () => {
    it("should generate valid payment URL", () => {
      const paymentUrl = payfast.getPaymentUrl({
        orderId: testOrderId,
        amount: 500,
        customerEmail: "payment@test.com",
        customerName: "Payment Tester",
        itemName: `Invoice for Order #${testOrderId}`,
        itemDescription: "Payment for DTF printing order",
        returnUrl: "https://example.com/return",
        cancelUrl: "https://example.com/cancel",
        notifyUrl: "https://example.com/notify",
      });

      expect(paymentUrl).toContain("sandbox.payfast.co.za");
      expect(paymentUrl).toContain("merchant_id=test-merchant");
      expect(paymentUrl).toContain("amount=500.00");
      expect(paymentUrl).toContain("signature=");
    });

    it("should generate correct MD5 signature", () => {
      const data = {
        merchant_id: "test-merchant",
        merchant_key: "test-key",
        amount: "100.00",
      };

      const url = payfast.getPaymentUrl({
        orderId: 1,
        amount: 100,
        customerEmail: "test@example.com",
        customerName: "Test User",
        itemName: "Test Item",
        itemDescription: "Test Description",
        returnUrl: "https://example.com/return",
        cancelUrl: "https://example.com/cancel",
        notifyUrl: "https://example.com/notify",
      });

      expect(url).toContain("signature=");
    });

    it("should verify valid notification signature", () => {
      // This is a simplified test - in production, you'd use actual PayFast notifications
      const notification = {
        m_payment_id: "order-1",
        pf_payment_id: "123456",
        payment_status: "COMPLETE",
        amount_gross: "500.00",
        amount_fee: "10.00",
        amount_net: "490.00",
        custom_int1: "1",
        custom_str1: "test@example.com",
        name_first: "Test",
        name_last: "User",
        email_address: "test@example.com",
        merchant_id: "test-merchant",
        signature: "", // Would be generated by PayFast
      };

      // Signature verification requires actual PayFast data
      // This test validates the method exists
      const isValid = payfast.verifyNotificationSignature(notification as any);
      expect(typeof isValid).toBe("boolean");
    });
  });

  describe("Manual Payment Submission", () => {
    it("should record manual payment submission", async () => {
      const beforeUpdate = await db
        .select()
        .from(orders)
        .where(eq(orders.id, testOrderId))
        .limit(1);

      expect(beforeUpdate[0].paymentVerificationStatus).toBe("pending");

      // Simulate manual payment submission
      await db
        .update(orders)
        .set({
          paymentVerificationStatus: "pending",
          paymentVerificationNotes: "EFT payment submitted. Proof: https://example.com/proof.pdf",
          updatedAt: new Date(),
        })
        .where(eq(orders.id, testOrderId));

      const afterUpdate = await db
        .select()
        .from(orders)
        .where(eq(orders.id, testOrderId))
        .limit(1);

      expect(afterUpdate[0].paymentVerificationStatus).toBe("pending");
      expect(afterUpdate[0].paymentVerificationNotes).toContain("EFT payment submitted");
    });

    it("should track payment verification status", async () => {
      // Update to verified
      await db
        .update(orders)
        .set({
          paymentVerificationStatus: "verified",
          paymentStatus: "paid",
          amountPaid: "500.00",
          paymentVerificationNotes: "Payment verified by admin",
          updatedAt: new Date(),
        })
        .where(eq(orders.id, testOrderId));

      const order = await db
        .select()
        .from(orders)
        .where(eq(orders.id, testOrderId))
        .limit(1);

      expect(order[0].paymentVerificationStatus).toBe("verified");
      expect(order[0].paymentStatus).toBe("paid");
      expect(parseFloat(order[0].amountPaid)).toBe(500);
    });

    it("should handle payment rejection", async () => {
      // Create another test order
      const result = await db.insert(orders).values({
        productId: 1,
        colorId: 1,
        sizeId: 1,
        quantity: 5,
        customerFirstName: "Reject",
        customerLastName: "Test",
        customerEmail: "reject@test.com",
        customerPhone: "4444444444",
        totalPriceEstimate: "500.00",
        depositAmount: "250.00",
        paymentMethod: "deposit",
        paymentStatus: "unpaid",
        status: "approved",
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      const rejectOrderId = result[0].insertId;

      // Simulate rejection
      await db
        .update(orders)
        .set({
          paymentVerificationStatus: "rejected",
          paymentVerificationNotes: "Payment proof invalid - please resubmit",
          updatedAt: new Date(),
        })
        .where(eq(orders.id, rejectOrderId));

      const order = await db
        .select()
        .from(orders)
        .where(eq(orders.id, rejectOrderId))
        .limit(1);

      expect(order[0].paymentVerificationStatus).toBe("rejected");
      expect(order[0].paymentVerificationNotes).toContain("invalid");

      // Cleanup
      await db.delete(orders).where(eq(orders.id, rejectOrderId));
    });
  });

  describe("Payment Status Tracking", () => {
    it("should calculate remaining balance correctly", async () => {
      const order = await db
        .select()
        .from(orders)
        .where(eq(orders.id, testOrderId))
        .limit(1);

      const totalAmount = parseFloat(order[0].totalPriceEstimate);
      const amountPaid = parseFloat(order[0].amountPaid || "0");
      const remainingBalance = totalAmount - amountPaid;

      expect(remainingBalance).toBeGreaterThanOrEqual(0);
      expect(remainingBalance).toBeLessThanOrEqual(totalAmount);
    });

    it("should track multiple partial payments", async () => {
      // First payment
      await db
        .update(orders)
        .set({
          amountPaid: "300.00",
          paymentStatus: "deposit_paid",
          updatedAt: new Date(),
        })
        .where(eq(orders.id, testOrderId));

      let order = await db
        .select()
        .from(orders)
        .where(eq(orders.id, testOrderId))
        .limit(1);

      expect(parseFloat(order[0].amountPaid)).toBe(300);
      expect(order[0].paymentStatus).toBe("deposit_paid");

      // Second payment (full payment)
      await db
        .update(orders)
        .set({
          amountPaid: "1000.00",
          paymentStatus: "paid",
          updatedAt: new Date(),
        })
        .where(eq(orders.id, testOrderId));

      order = await db
        .select()
        .from(orders)
        .where(eq(orders.id, testOrderId))
        .limit(1);

      expect(parseFloat(order[0].amountPaid)).toBe(1000);
      expect(order[0].paymentStatus).toBe("paid");
    });

    it("should prevent overpayment", async () => {
      const order = await db
        .select()
        .from(orders)
        .where(eq(orders.id, testOrderId))
        .limit(1);

      const totalAmount = parseFloat(order[0].totalPriceEstimate);
      const amountPaid = parseFloat(order[0].amountPaid || "0");

      // Ensure payment doesn't exceed total
      const validPaymentAmount = Math.min(amountPaid + 100, totalAmount);
      expect(validPaymentAmount).toBeLessThanOrEqual(totalAmount);
    });
  });

  describe("Payment Verification Workflow", () => {
    it("should transition from pending to verified", async () => {
      const statuses = ["pending", "verified"];

      for (const status of statuses) {
        await db
          .update(orders)
          .set({
            paymentVerificationStatus: status as any,
            updatedAt: new Date(),
          })
          .where(eq(orders.id, testOrderId));

        const order = await db
          .select()
          .from(orders)
          .where(eq(orders.id, testOrderId))
          .limit(1);

        expect(order[0].paymentVerificationStatus).toBe(status);
      }
    });

    it("should store verification notes", async () => {
      const testNotes = "Payment verified via bank transfer on 2026-03-26";

      await db
        .update(orders)
        .set({
          paymentVerificationNotes: testNotes,
          updatedAt: new Date(),
        })
        .where(eq(orders.id, testOrderId));

      const order = await db
        .select()
        .from(orders)
        .where(eq(orders.id, testOrderId))
        .limit(1);

      expect(order[0].paymentVerificationNotes).toBe(testNotes);
    });
  });
});
